{
    "openapi": "3.0.0",
    "info": {
        "title": "Forwarder API",
        "version": "1.0.0"
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    },
    "security": [
        {
            "bearerAuth": []
        }
    ],
    "paths": {
        "/api/auth/register": {
            "post": {
                "tags" : ["Auth"],
                "summary": "User Registration",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "description": "User's name",
                                        "example": "John Doe"
                                    },
                                    "phone": {
                                        "type": "string",
                                        "description": "User's phone number",
                                        "example": "+1234567890"
                                    },
                                    "email": {
                                        "type": "string",
                                        "description": "User's email address",
                                        "example": "john@example.com"
                                    },
                                    "user_role_id": {
                                        "type": "integer",
                                        "description": "User's role ID",
                                        "example": 1
                                    },
                                    "standard": {
                                        "type": "string",
                                        "description": "Standard User information",
                                        "example": {
                                            "lastName" : "doe",
                                            "private_number" : "59009102",
                                            "position" : "CTO"
                                        }
                                    },
                                    "driver": {
                                        "type": "string",
                                        "description": "Driver information",
                                        "example": {
                                            "telegram" : "59009102",
                                            "whatsapp" : "59009102",
                                            "viber" : "59009102",
                                            "referral_code" : "a134",
                                            "iban" : "GE34BG132134",
                                            "car_id" : 1,
                                            "trailer_id" : 1
                                        }
                                    },
                                    "legal": {
                                        "type": "string",
                                        "description": "Legal entity information",
                                        "example": {
                                            "identification_code" : "59009102",
                                            "company_name" : "re:soft",
                                            "company_ceo_name" : "Lasha",
                                            "contact_number" : "252452"
                                        }
                                    },
                                    "forwarder": {
                                        "type": "string",
                                        "description": "Forwarder information",
                                        "example": {
                                            "identification_code" : "59009102",
                                            "company_name" : "re:soft",
                                            "company_ceo_name" : "Lasha",
                                            "contact_number" : "252452"
                                        }
                                    },
                                    "customer": {
                                        "type": "string",
                                        "description": "Customer information",
                                        "example": {
                                            "identification_code" : "59009102",
                                            "company_name" : "re:soft",
                                            "company_ceo_name" : "Lasha",
                                            "contact_number" : "252452"
                                        }
                                    },
                                    "id" : {
                                        "type" : "integer",
                                        "description" : "Use id to update user details",
                                        "example" : 4
                                    },
                                    "languages" : {
                                        "type" : "array",
                                        "description" : "User Languages",
                                        "example" : [1,2,3,4]
                                    },
                                    "images": {
                                        "type": "string",
                                        "description": "Image URLs",
                                        "example": [
                                            {
                                                "title" : "drivers_license",
                                                "url" : "https://shorturl.at/moNP0"
                                            },
                                            {
                                                "title" : "tech_passport",
                                                "url" : "https://shorturl.at/moNP0"
                                            },
                                            {
                                                "title" : "passport",
                                                "url" : "https://shorturl.at/moNP0"
                                            },
                                            {
                                                "title" : "residence_confirmation",
                                                "url" : "https://shorturl.at/moNP0"
                                            },
                                            {
                                                "title" : "bank_credentials",
                                                "url" : "https://shorturl.at/moNP0"
                                            }
                                        ]
                                    }
                                },
                                "required": ["name", "phone", "email"]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "User registration successful"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/auth/verify": {
            "post": {
                "tags" : ["Auth"],
                "summary": "Verify User",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "user_id": {
                                        "type": "integer",
                                        "description": "User ID",
                                        "example": 123
                                    },
                                    "otp": {
                                        "type": "integer",
                                        "description": "verification Code",
                                        "example": 123456
                                    }
                                },
                                "required": ["user_id", "otp"]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "User Verified successful"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/auth/get-login-code": {
            "post": {
                "tags" : ["Auth"],
                "summary": "Get Login code",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "phone": {
                                        "type": "string",
                                        "description": "User Phone number",
                                        "example": "+1234567890"
                                    }
                                },
                                "required": ["phone"]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Code sent successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "tags" : ["Auth"],
                "summary": "Login User with code",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "phone": {
                                        "type": "string",
                                        "description": "User Phone number",
                                        "example": "+1234567890"
                                    },
                                    "otp": {
                                        "type": "string",
                                        "description": "User OTP code",
                                        "example": "123456"
                                    }
                                },
                                "required": ["phone", "otp"]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "User Logged in successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/auth/user-roles": {
            "get": {
                "tags" : ["Auth"],
                "summary": "User Roles",
                "responses": {
                    "200": {
                        "description": "User Roles fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/user": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "tags" : ["Current User"],
                "summary": "Current User",
                "responses": {
                    "200": {
                        "description": "Current user fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/car-types": {
            "get": {
                "tags" : ["Car"],
                "summary": "Car types",
                "responses": {
                    "200": {
                        "description": "Car types fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/trailer-types": {
            "get": {
                "tags" : ["Trailer"],
                "summary": "Trailer types",
                "responses": {
                    "200": {
                        "description": "Trailer types fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/rs/tax-payer/{code}": {
            "get": {
                "tags" : ["RS"],
                "summary": "Tax payer info",
                "parameters": [
                    {
                        "in": "path",
                        "name": "code",
                        "description": "Tax payer code",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "default": "206322102"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tax Payer info fetched successfully"
                    },
                    "400": {
                        "description": "Bad request - Invalid input data"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        }
    }
}
